{
 "title": "Fitness Tracker",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Hello!",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "insight",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Average Pace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"runs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"run\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pace\")\r\n  |> filter(fn: (r) => r[\"user_id\"] == \"u12345\")"
    }
   ]
  },
  {
   "title": "Average Heart Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"runs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"run\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heart_rate\")\r\n  |> filter(fn: (r) => r[\"user_id\"] == \"u12345\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"runs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"run\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heart_rate\")\r\n  |> filter(fn: (r) => r[\"user_id\"] == \"u12345\")"
    }
   ]
  },
  {
   "title": "Pace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"runs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"run\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pace\")\r\n  |> filter(fn: (r) => r[\"user_id\"] == \"u12345\")"
    }
   ]
  }
 ]
}